# makefile to build all macOS related plugins in this plugin project.

all:
	$(MAKE) -C leechcore_ft601_driver_macos -f Makefile.macos
	$(MAKE) -C leechcore_device_rawtcp -f Makefile.macos
	$(MAKE) -C leechcore_device_skeleton -f Makefile.macos

clean:
	$(MAKE) -C leechcore_ft601_driver_macos -f Makefile.macos clean
	$(MAKE) -C leechcore_device_rawtcp  -f Makefile.macos clean
	$(MAKE) -C leechcore_device_skeleton -f Makefile.macos clean
